// 宏观指标元数据（中国/美国）
// 采集配置与展示元数据统一维护，采集脚本（scripts/fetch-indicators.mjs）与前端共用

export type Region = 'CN' | 'US';
export type Direction = 'up_good' | 'down_good' | 'neutral';
export type IndicatorStatus = 'active' | 'pending';

export interface FetchConfig {
  /** cn_report: 东方财富中国报表; cn_rate: 东方财富利率报表（如 LPR）; us_indicator: 东方财富美国指标库; fred: FRED CSV（日/月频，取月末值）; cn_kline: 东方财富行情 K 线（日频，取月末值） */
  kind: 'cn_report' | 'cn_rate' | 'us_indicator' | 'fred' | 'cn_kline' | null;
  /** cn: 报表名; us: INDICATOR_ID; fred: FRED 序列号; kline: secid */
  ref: string;
  /** cn: 取值字段名 */
  field?: string;
  /** 数值单位换算系数（乘以此系数转为展示单位） */
  unitMult?: number;
  /** 特殊计算 */
  calc?: 'gdp_annualized' | 'div_10' | 'div_100';
  /** 数据异常的日期（YYYY-MM），采集时强制置空不展示 */
  exclude?: string[];
}

export interface IndicatorMeta {
  code: string;
  region: Region;
  regionName: string;
  /** 指标名（展示用） */
  name: string;
  /** 短名（热力图坐标轴用） */
  shortName: string;
  /** 跨地区对比主题（同主题不同地区可对比，如 GDP 主题 = CN_GDP + US_GDP） */
  theme: string;
  /** 主题名（对比图用） */
  themeName: string;
  category: string;
  unit: string;
  direction: Direction;
  /** 颜色映射中心值（如 PMI=50、同比=0） */
  neutral: number;
  status: IndicatorStatus;
  agency: string;
  frequency: string;
  /** 发布滞后说明 */
  lag: string;
  definition: string;
  note: string;
  fetch: FetchConfig;
}

export const REGIONS: { code: Region; name: string }[] = [
  { code: 'CN', name: '中国' },
  { code: 'US', name: '美国' },
];

export const INDICATOR_META: IndicatorMeta[] = [
  // ================= 中国（10 项） =================
  {
    code: 'CN_GDP',
    region: 'CN',
    regionName: '中国',
    name: '国内生产总值（GDP）同比',
    shortName: 'GDP',
    theme: 'gdp',
    themeName: '国内生产总值（GDP）增速',
    category: '增长',
    unit: '%',
    direction: 'up_good',
    neutral: 0,
    status: 'active',
    agency: '国家统计局',
    frequency: '季度',
    lag: '季后约 2 周发布',
    definition: '一定时期内一国境内生产的最终产品和劳务的市场价值，反映整体经济规模与增速。',
    note: '公布的是当季同比增速，与累计同比口径略有差异；季度数据波动小于月度指标。',
    fetch: { kind: 'cn_report', ref: 'RPT_ECONOMY_GDP', field: 'SUM_SAME' },
  },
  {
    code: 'CN_INDUSTRY',
    region: 'CN',
    regionName: '中国',
    name: '规模以上工业增加值同比',
    shortName: '工业增加值',
    theme: 'industry',
    themeName: '工业增加值 / 工业产出',
    category: '增长',
    unit: '%',
    direction: 'up_good',
    neutral: 0,
    status: 'active',
    agency: '国家统计局',
    frequency: '月度',
    lag: '月后约 2 周发布',
    definition: '规模以上工业企业（年主营业务收入 2000 万元以上）生产活动的价值增量，反映制造业景气。',
    note: '东方财富口径为当月同比；受春节错位影响 1-2 月波动较大，宜看累计或移动平均。',
    fetch: { kind: 'cn_report', ref: 'RPT_ECONOMY_INDUS_GROW', field: 'BASE_SAME' },
  },
  {
    code: 'CN_CPI',
    region: 'CN',
    regionName: '中国',
    name: '居民消费价格指数（CPI）同比',
    shortName: 'CPI',
    theme: 'cpi',
    themeName: '居民消费价格（CPI / 核心 CPI）',
    category: '价格',
    unit: '%',
    direction: 'neutral',
    neutral: 0,
    status: 'active',
    agency: '国家统计局',
    frequency: '月度',
    lag: '月后 10 日左右发布',
    definition: '反映居民家庭购买消费品和服务价格水平的变动，是衡量通胀的核心指标。',
    note: '同比受基期影响；猪肉、能源等分项波动大，常被引为物价读数的主要扰动。',
    fetch: { kind: 'cn_report', ref: 'RPT_ECONOMY_CPI', field: 'NATIONAL_SAME' },
  },
  {
    code: 'CN_PPI',
    region: 'CN',
    regionName: '中国',
    name: '工业生产者出厂价格指数（PPI）同比',
    shortName: 'PPI',
    theme: 'ppi',
    themeName: '生产者价格（PPI / 核心 PPI）',
    category: '价格',
    unit: '%',
    direction: 'neutral',
    neutral: 0,
    status: 'active',
    agency: '国家统计局',
    frequency: '月度',
    lag: '月后 10 日左右发布',
    definition: '工业企业产品出厂价格的变动，反映上游工业品价格与工业盈利环境。',
    note: 'PPI 与工业利润、库存周期相关性强；持续为负通常意味着工业部门通缩压力。',
    fetch: { kind: 'cn_report', ref: 'RPT_ECONOMY_PPI', field: 'BASE_SAME' },
  },
  {
    code: 'CN_PMI',
    region: 'CN',
    regionName: '中国',
    name: '制造业采购经理指数（PMI）',
    shortName: 'PMI',
    theme: 'pmi',
    themeName: '制造业采购经理指数（PMI / ISM）',
    category: '景气',
    unit: '指数',
    direction: 'up_good',
    neutral: 50,
    status: 'active',
    agency: '国家统计局',
    frequency: '月度',
    lag: '月末最后一日发布',
    definition: '基于制造业企业采购经理调查的扩散指数，50 为荣枯线，高于 50 扩张、低于 50 收缩。',
    note: '调查样本以大型企业为主，对小企业景气反映有限；可与财新 PMI 对照观察。',
    fetch: { kind: 'cn_report', ref: 'RPT_ECONOMY_PMI', field: 'MAKE_INDEX' },
  },
  {
    code: 'CN_RETAIL',
    region: 'CN',
    regionName: '中国',
    name: '社会消费品零售总额同比',
    shortName: '社零总额',
    theme: 'consumption',
    themeName: '消费（社零总额 / 零售销售）',
    category: '消费',
    unit: '%',
    direction: 'up_good',
    neutral: 0,
    status: 'active',
    agency: '国家统计局',
    frequency: '月度',
    lag: '月后约 2 周发布',
    definition: '企业销售给个人和社会集团的实物商品金额，以及餐饮收入，反映居民消费需求。',
    note: '不含服务消费（线上服务、教育医疗等）；汽车、家电等大宗消费占比高，波动较大。',
    fetch: { kind: 'cn_report', ref: 'RPT_ECONOMY_TOTAL_RETAIL', field: 'RETAIL_TOTAL_SAME' },
  },
  {
    code: 'CN_INVEST',
    region: 'CN',
    regionName: '中国',
    name: '固定资产投资同比',
    shortName: '固投',
    theme: 'investment',
    themeName: '固定资产投资',
    category: '投资',
    unit: '%',
    direction: 'up_good',
    neutral: 0,
    status: 'active',
    agency: '国家统计局',
    frequency: '月度',
    lag: '月后约 2 周发布',
    definition: '固定资产投资（不含农户）的规模变化，基建、制造业、房地产三分天下，反映投资需求。',
    note: '东方财富口径为当月同比；官方常公布累计同比，两者差异需注意，宜比较历史趋势。',
    fetch: { kind: 'cn_report', ref: 'RPT_ECONOMY_ASSET_INVEST', field: 'BASE_SAME' },
  },
  {
    code: 'CN_EXPORT',
    region: 'CN',
    regionName: '中国',
    name: '出口金额同比',
    shortName: '出口',
    theme: 'trade',
    themeName: '外贸（出口金额 / 贸易差额）',
    category: '外贸',
    unit: '%',
    direction: 'up_good',
    neutral: 0,
    status: 'active',
    agency: '海关总署',
    frequency: '月度',
    lag: '月后约 1 周发布',
    definition: '以美元计价的出口金额同比，反映外需与出口竞争力，是净出口对 GDP 贡献的先导。',
    note: '以美元计价受汇率影响；春节错位导致 1-2 月波动大，应结合累计数据判断趋势。',
    fetch: { kind: 'cn_report', ref: 'RPT_ECONOMY_CUSTOMS', field: 'EXIT_BASE_SAME' },
  },
  {
    code: 'CN_M2',
    region: 'CN',
    regionName: '中国',
    name: '广义货币供应量（M2）同比',
    shortName: 'M2',
    theme: 'money',
    themeName: '广义货币供应量（M2）',
    category: '货币',
    unit: '%',
    direction: 'neutral',
    neutral: 0,
    status: 'active',
    agency: '中国人民银行',
    frequency: '月度',
    lag: '月后 10-15 日发布',
    definition: '流通中现金 + 活期存款 + 定期存款 + 储蓄存款等，衡量全社会货币总量，反映货币宽松程度。',
    note: 'M2 增速是货币政策松紧的指示器；与名义 GDP 增速之差可粗略反映流动性充裕程度。',
    fetch: { kind: 'cn_report', ref: 'RPT_ECONOMY_CURRENCY_SUPPLY', field: 'BASIC_CURRENCY_SAME' },
  },
  {
    code: 'CN_SF',
    region: 'CN',
    regionName: '中国',
    name: '社会融资规模增量',
    shortName: '社融',
    theme: 'financing',
    themeName: '社会融资规模增量',
    category: '货币',
    unit: '亿元',
    direction: 'neutral',
    neutral: 0,
    status: 'pending',
    agency: '中国人民银行',
    frequency: '月度',
    lag: '月后 10-15 日发布',
    definition: '实体经济从金融体系获得的资金总量，包括信贷、债券、股票、信托等，反映信用扩张力度。',
    note: '数据源待接入（东方财富暂未提供该报表，央行无公开 API），后续可尝试接入 FRED 或官方爬取。',
    fetch: { kind: null, ref: '' },
  },
  {
    code: 'CN_10Y',
    region: 'CN',
    regionName: '中国',
    name: '10 年期国债收益率',
    shortName: '10Y国债',
    theme: 'bondyield',
    themeName: '10 年期国债收益率',
    category: '利率',
    unit: '%',
    direction: 'neutral',
    neutral: 0,
    status: 'active',
    agency: '中央结算公司（中债估值）',
    frequency: '月度',
    lag: '交易日更新，取月末值',
    definition: '10 年期记账式国债的到期收益率，是债券市场定价的锚，代表长期无风险利率水平。',
    note: '由日度行情取每月最后一个交易日的收益率（月末值）。数据经东方财富行情接口获取，数据源偶发波动时当月可能缺失。',
    fetch: { kind: 'cn_kline', ref: '171.CN10Y' },
  },
  {
    code: 'CN_LPR1Y',
    region: 'CN',
    regionName: '中国',
    name: '贷款市场报价利率（LPR）：1 年期',
    shortName: 'LPR 1年',
    theme: 'lpr',
    themeName: '贷款市场报价利率（LPR）',
    category: '利率',
    unit: '%',
    direction: 'neutral',
    neutral: 0,
    status: 'active',
    agency: '全国银行间同业拆借中心',
    frequency: '月度',
    lag: '每月 20 日发布',
    definition: '贷款市场报价利率（LPR）1 年期品种，由报价行基于公开市场操作利率加点形成，是短期贷款利率的基准。',
    note: 'LPR 改革后每月 20 日（遇节假日顺延）发布，实际发布次数少于 12 次/年；1 年期主要锚定企业短期信贷成本。',
    fetch: { kind: 'cn_rate', ref: 'RPTA_WEB_RATE', field: 'LPR1Y' },
  },
  {
    code: 'CN_LPR5Y',
    region: 'CN',
    regionName: '中国',
    name: '贷款市场报价利率（LPR）：5 年期以上',
    shortName: 'LPR 5年',
    theme: 'lpr',
    themeName: '贷款市场报价利率（LPR）',
    category: '利率',
    unit: '%',
    direction: 'neutral',
    neutral: 0,
    status: 'active',
    agency: '全国银行间同业拆借中心',
    frequency: '月度',
    lag: '每月 20 日发布',
    definition: '贷款市场报价利率（LPR）5 年期以上品种，是房贷利率的主要定价基准，反映长期信贷成本。',
    note: '5 年期以上 LPR 调整频率低于 1 年期；房贷重定价周期多为 1 年，LPR 下调对存量房贷的影响存在时滞。',
    fetch: { kind: 'cn_rate', ref: 'RPTA_WEB_RATE', field: 'LPR5Y' },
  },

  // ================= 美国（12 项） =================
  {
    code: 'US_GDP',
    region: 'US',
    regionName: '美国',
    name: 'GDP 环比折年率',
    shortName: 'GDP',
    theme: 'gdp',
    themeName: 'GDP 增长',
    category: '增长',
    unit: '%',
    direction: 'up_good',
    neutral: 0,
    status: 'active',
    agency: '美国经济分析局（BEA）',
    frequency: '季度',
    lag: '季后首月发布（初值-修正-终值）',
    definition: '美国实际 GDP 环比增速折算为全年水平，是市场最关注的美国增长读数。',
    note: '原始数据为环比，已由脚本换算为折年率（(1+环比)^4-1）；初值会经历两次修正。2020 年二、三季度受疫情冲击数据失真，已置空。',
    fetch: { kind: 'us_indicator', ref: 'EMG00159633', calc: 'gdp_annualized', exclude: ['2020-06', '2020-09'] },
  },
  {
    code: 'US_CORE_CPI',
    region: 'US',
    regionName: '美国',
    name: '核心 CPI 同比',
    shortName: '核心CPI',
    theme: 'cpi',
    themeName: '居民消费价格（CPI / 核心 CPI）',
    category: '价格',
    unit: '%',
    direction: 'neutral',
    neutral: 0,
    status: 'active',
    agency: '美国劳工统计局（BLS）',
    frequency: '月度',
    lag: '月后 2 周左右发布',
    definition: '剔除食品与能源的 CPI 同比，是美联储评估潜在通胀压力的核心参考。',
    note: '核心 CPI 替代核心 PCE（口径最接近）；美联储更偏好 PCE，两者走势通常同步。',
    fetch: { kind: 'us_indicator', ref: 'EMG00000746' },
  },
  {
    code: 'US_PPI',
    region: 'US',
    regionName: '美国',
    name: '核心 PPI 同比',
    shortName: '核心PPI',
    theme: 'ppi',
    themeName: '生产者价格（PPI / 核心 PPI）',
    category: '价格',
    unit: '%',
    direction: 'neutral',
    neutral: 0,
    status: 'active',
    agency: '美国劳工统计局（BLS）',
    frequency: '月度',
    lag: '月后 2 周左右发布',
    definition: '剔除食品与能源的生产者出厂价格同比，反映工业品价格与成本端压力。',
    note: '东方财富美国库提供核心 PPI 同比（非季调），口径与整体 PPI 略有差异。',
    fetch: { kind: 'us_indicator', ref: 'EMG00177799' },
  },
  {
    code: 'US_UNEMP',
    region: 'US',
    regionName: '美国',
    name: '失业率',
    shortName: '失业率',
    theme: 'employment',
    themeName: '失业率',
    category: '就业',
    unit: '%',
    direction: 'down_good',
    neutral: 5,
    status: 'active',
    agency: '美国劳工统计局（BLS）',
    frequency: '月度',
    lag: '月后首个周五发布',
    definition: '失业人口占劳动力人口的比例，是衡量劳动力市场紧张程度的基石指标。',
    note: '失业率低意味着就业市场强劲；过低（低于自然失业率）可能引发通胀与加息压力。',
    fetch: { kind: 'us_indicator', ref: 'EMG00001039' },
  },
  {
    code: 'US_NONFARM',
    region: 'US',
    regionName: '美国',
    name: '新增非农就业人数',
    shortName: '非农',
    theme: 'nonfarm',
    themeName: '新增非农就业人数',
    category: '就业',
    unit: '万人',
    direction: 'up_good',
    neutral: 0,
    status: 'active',
    agency: '美国劳工统计局（BLS）',
    frequency: '月度',
    lag: '月后首个周五发布',
    definition: '剔除农业部门后新增的就业人数，反映企业用工需求与经济动能。',
    note: '原始单位为千人，已由脚本换算为万人；单月数据噪音大，建议看 3 个月移动平均。',
    fetch: { kind: 'us_indicator', ref: 'EMG00152118', calc: 'div_10' },
  },
  {
    code: 'US_ISM',
    region: 'US',
    regionName: '美国',
    name: 'ISM 制造业 PMI',
    shortName: 'ISM PMI',
    theme: 'pmi',
    themeName: '制造业采购经理指数（PMI / ISM）',
    category: '景气',
    unit: '指数',
    direction: 'up_good',
    neutral: 50,
    status: 'active',
    agency: '美国供应管理协会（ISM）',
    frequency: '月度',
    lag: '月后首日发布',
    definition: '美国制造业采购经理调查扩散指数，50 为荣枯线，反映制造业扩张与收缩。',
    note: '与官方 Markit PMI 调查对象不同；低于 45 通常预示制造业深度收缩。',
    fetch: { kind: 'us_indicator', ref: 'EMG00002790' },
  },
  {
    code: 'US_FEDRATE',
    region: 'US',
    regionName: '美国',
    name: '联邦基金目标利率（上限）',
    shortName: '联邦基金利率',
    theme: 'rate',
    themeName: '联邦基金目标利率',
    category: '货币',
    unit: '%',
    direction: 'neutral',
    neutral: 0,
    status: 'active',
    agency: '美联储（FOMC）',
    frequency: '月度',
    lag: 'FOMC 会议后即时',
    definition: '美联储货币政策目标区间的上限，直接反映政策利率水平与货币政策立场。',
    note: '目标区间而非实际成交利率；对债市、汇市与风险资产定价有全局影响。',
    fetch: { kind: 'us_indicator', ref: 'EMG00342250' },
  },
  {
    code: 'US_RETAIL',
    region: 'US',
    regionName: '美国',
    name: '零售销售环比',
    shortName: '零售销售',
    theme: 'consumption',
    themeName: '消费（社零总额 / 零售销售）',
    category: '消费',
    unit: '%',
    direction: 'up_good',
    neutral: 0,
    status: 'active',
    agency: '美国商务部普查局',
    frequency: '月度',
    lag: '月后 2 周左右发布',
    definition: '零售和食品服务销售额的环比变化，是消费支出（美国 GDP 最大构成）的月度先导。',
    note: '季调环比；不含大部分服务消费，节日促销等会造成单月波动。',
    fetch: { kind: 'us_indicator', ref: 'EMG00003721' },
  },
  {
    code: 'US_TRADE',
    region: 'US',
    regionName: '美国',
    name: '贸易差额',
    shortName: '贸易差额',
    theme: 'trade',
    themeName: '外贸（出口金额 / 贸易差额）',
    category: '外贸',
    unit: '亿美元',
    direction: 'neutral',
    neutral: 0,
    status: 'active',
    agency: '美国商务部普查局',
    frequency: '月度',
    lag: '月后约 1 周发布',
    definition: '商品与服务出口减进口的差额，负值表示逆差，反映净出口对增长的拖累或贡献。',
    note: '原始单位为百万美元，已由脚本换算为亿美元；逆差扩大通常拖累 GDP。',
    fetch: { kind: 'us_indicator', ref: 'EMG00000700', calc: 'div_100' },
  },
  {
    code: 'US_INDUSTRIAL',
    region: 'US',
    regionName: '美国',
    name: '工业产出同比',
    shortName: '工业产出',
    theme: 'industry',
    themeName: '工业增加值 / 工业产出',
    category: '增长',
    unit: '%',
    direction: 'up_good',
    neutral: 0,
    status: 'pending',
    agency: '美联储（Board of Governors）',
    frequency: '月度',
    lag: '月后 2 周左右发布',
    definition: '制造业、采矿业与公用事业产出指数同比，反映美国工业生产能力利用率。',
    note: '数据源待接入（东方财富美国库暂无该指标），后续可尝试接入 FRED。',
    fetch: { kind: null, ref: '' },
  },
  {
    code: 'US_JOBLESS',
    region: 'US',
    regionName: '美国',
    name: '初请失业金人数（周度）',
    shortName: '初请失业金',
    theme: 'jobless',
    themeName: '初请失业金人数',
    category: '就业',
    unit: '万人',
    direction: 'down_good',
    neutral: 0,
    status: 'pending',
    agency: '美国劳工部（DOL）',
    frequency: '周度',
    lag: '每周四发布',
    definition: '当周首次申请失业救济的人数，是就业市场最及时的高频监测指标。',
    note: '数据源待接入（东方财富美国库暂无该指标），后续可尝试接入 FRED。',
    fetch: { kind: null, ref: '' },
  },
  {
    code: 'US_10Y',
    region: 'US',
    regionName: '美国',
    name: '10 年期国债收益率',
    shortName: '10Y国债',
    theme: 'bondyield',
    themeName: '10 年期国债收益率',
    category: '利率',
    unit: '%',
    direction: 'neutral',
    neutral: 0,
    status: 'active',
    agency: '美联储（FRED DGS10）',
    frequency: '月度',
    lag: '交易日更新，取月末值',
    definition: '美国 10 年期国债的到期收益率，是全球资产定价的基准利率，反映长期增长与通胀预期。',
    note: '由日度行情取每月最后一个交易日的收益率（月末值）。数据来自美联储圣路易斯分行（FRED）DGS10 序列，1962 年至今。',
    fetch: { kind: 'fred', ref: 'DGS10' },
  },
];

export const metaByCode = new Map(INDICATOR_META.map((m) => [m.code, m]));

/** 按主题分组指标 */
export function groupByTheme(): Map<string, IndicatorMeta[]> {
  const map = new Map<string, IndicatorMeta[]>();
  for (const m of INDICATOR_META) {
    const list = map.get(m.theme) ?? [];
    list.push(m);
    map.set(m.theme, list);
  }
  return map;
}
